apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb2
        group: influx2-k8s
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.5.2
        ports:
        - name: http
          containerPort: 8086
#        volumeMounts:
#        - mountPath: "/var/lib/influxdb"
#          name: influxdb-data
#      volumes:
#        - name: influxdb-data
#          persistentVolumeClaim:
#           claimName: nfs-pvc-influxdb
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chronograf2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chronograf2
        group: influx2-k8s
    spec:
      containers:
      - name: chronograf
        image: chronograf
        ports:
        - name: http
          containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf2-ext
  labels:
    app: chronograf2
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: chronograf2
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb2-ext
  labels:
    app: influxdb2
spec:
  type: NodePort
  ports:
  - port: 8086
    protocol: TCP
  selector:
    app: influxdb2
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb2-int
  labels:
    app: influxdb2
spec:
  selector:
    app: influxdb2
  ports:
  - protocol: TCP
    port: 8086
    targetPort: http
