apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensehat-temperature
  labels:
    draft: sensehat-temperature-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        draft: sensehat-temperature-app
        app: sensehat-temperature
    spec:
      containers:
      - image: registry:5000/temperature
        name: sensehat-temperature
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      nodeSelector:
        sensehat: "true"
